/* Creaci�n de las tablas */

-- Tabla: CLIENTE
CREATE TABLE CLIENTE (
	IDCLI INTEGER,
    DNICLI CHAR(8),
    NOMCLI VARCHAR2(30),
	ESTCLI CHAR(1),
	CONSTRAINT CLIENTE_pk PRIMARY KEY(IDCLI)
);


/* Creaci�n de las secuencias */

-- Secuencia: ID_CLIENTE
CREATE SEQUENCE ID_CLIENTE START WITH 1 INCREMENT BY 1 ORDER;


/* Creaci�n de los Triggers */

-- Trigger: ID_CLIENTE
CREATE OR REPLACE TRIGGER ID_CLIENTE BEFORE INSERT ON CLIENTE FOR EACH ROW BEGIN SELECT ID_CLIENTE.NEXTVAL INTO :NEW.IDCLI FROM DUAL;
END;
/

/* Inserci�n de datos */

-- INSERTAR REGISTROS DE CLIENTE
INSERT INTO CLIENTE (DNICLI,NOMCLI,ESTCLI) VALUES ('12345678','Juan','A');


/* Listar datos */

-- LISTAR REGISTROS DE CLIENTE
SELECT * FROM CLIENTE;


/* Eliminar tabla */
--DROP TABLE CLIENTE;


/* Eliminar secuencia*/
--DROP SEQUENCE ID_CLIENTE;





--ORACLE CLOUD USUARIO DEVELOPER

-- Tabla: CLIENTE
CREATE TABLE DEVELOPER.CLIENTE (
	IDCLI INTEGER,
    DNICLI CHAR(8),
    NOMCLI VARCHAR2(30),
	ESTCLI CHAR(1),
	CONSTRAINT CLIENTE_pk PRIMARY KEY(IDCLI)
);

-- Secuencia: ID_CLIENTE
CREATE SEQUENCE DEVELOPER.ID_CLIENTE START WITH 1 INCREMENT BY 1 ORDER;

-- Trigger: ID_CLIENTE
CREATE OR REPLACE TRIGGER DEVELOPER.ID_CLIENTE BEFORE INSERT ON DEVELOPER.CLIENTE FOR EACH ROW BEGIN SELECT ID_CLIENTE.NEXTVAL INTO :NEW.IDCLI FROM DUAL;
END;
/

-- LISTAR REGISTROS DE CLIENTE
SELECT * FROM DEVELOPER.CLIENTE;


/* Eliminar tabla */
DROP TABLE DEVELOPER.CLIENTE;

/* Eliminar secuencia*/
DROP SEQUENCE DEVELOPER.ID_CLIENTE;
