server:
  port: ${PORT:8085}  # puerto 8085 por defecto si no se define en las variables de entorno

spring:
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@developer_medium?TNS_ADMIN=Wallet_developer}
    username: ${DB_USERNAME:DEVELOPER_01}
    password: ${DB_PASSWORD:Admin12345678}
    driver-class-name: ${DB_DRIVER:oracle.jdbc.OracleDriver}
  jpa:
    hibernate:
      ddl-auto: none   # none | update | create | create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: VGhpcy1pcy1hLXZlcnktc2VjdXJlLXNlY3JldC1rZXktZm9yLUpXVHMtMjAyNQ==  #Clave secreta: al menos 32 caracteres seguros (no uses palabras simples)
  expiration: '3600000' # 1 hora en milisegundos
aes:
  secret: '1234567890123456'