server:
  port: 8085
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: backend
  datasource:
    url: jdbc:oracle:thin:@dbdemo_medium?TNS_ADMIN=Wallet_DBDEMO
    username: DEVELOPER
    password: 12345
    driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@localhost:1521:xe
    #username: dbDemo
    #password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  main:
    allow-bean-definition-overriding: true
