server:
  port: 8084

spring:
  application:
    name: backend
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: dbDemo
    password: 12345
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
  main:
    allow-bean-definition-overriding: true